Update Fault Proof contract addresses for Sepolia
base/web pull request #1167
Opened 2024-10-28 16:01 UTC by cbfyi

**What changed? Why?**

Post-Granite, new implementation contracts were deployed, but their new addresses were not reflected in the docs.

**Notes to reviewers**

Related to https://github.com/ethereum-optimism/superchain-ops/tree/main/tasks/sep/base-004-fp-audit-fixes and https://github.com/base-org/contract-deployments/pull/214

**How has it been tested?**

It is quite simple to independently verify.
The `DisputeGameFactoryProxy` should not have changed.

Staring with the game implementations, simply call the read method, `gameImpls(uint32)`, to get the implementation for game type 0 (`FaultDisputeGame`), and 1 (`PermissionedDisputeGame`).

From those addresses, you can then call the game implementations to get the `MIPS` / VM (`vm()`), and `DelayedWETHProxy` (`weth()`) addresses.

Sample command:

    cast call --rpc-url <ETH Sepolia RPC URL> 0xd6E6dBf4F7EA0ac412fD8b65ED297e64BB7a06E1 "gameImpls(uint32)" 0

The `AnchorStateRegistryProxy` should remain unchanged as well.

2024-10-28 16:01 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-10-28 19:43 UTC, awilliams1-cb requested changes

2024-10-28 19:43 UTC, awilliams1-cb commented on apps/base-docs/docs/building-with-base/base-contracts.md
> +| DelayedWETHProxy             | [0x489c2E5ebe0037bDb2DC039C5770757b8E54eA1F](https://sepolia.etherscan.io/address/0x489c2E5ebe0037bDb2DC039C5770757b8E54eA1F) |
The current list only includes the `DelayedWETHProxy` for the `FaultDisputeGame` contract, so we need to add the `PermissionedDisputeGame` one as well:
```suggestion
| DelayedWETHProxy (FDG)       | [0x489c2E5ebe0037bDb2DC039C5770757b8E54eA1F](https://sepolia.etherscan.io/address/0x489c2E5ebe0037bDb2DC039C5770757b8E54eA1F) |
| DelayedWETHProxy (PDG)       | [0x27A6128F707de3d99F89Bf09c35a4e0753E1B808](https://sepolia.etherscan.io/address/0x27A6128F707de3d99F89Bf09c35a4e0753E1B808) |
```

2024-10-28 19:43 UTC, cb-heimdall commented
Review Error for awilliams1-cb @ 2024-10-28 19:43:48 UTC
User must have write permissions to review

2024-10-28 22:03 UTC, awilliams1-cb approved these changes

2024-10-29 13:45 UTC, wbnns approved these changes

2024-10-29 13:45 UTC, merged