Fix Typos and Minor Issues in Multiple Files
base/web pull request #1187
Opened 2024-11-01 14:56 UTC by dsarfed

This Pull Request addresses various typographical errors and minor issues across multiple files in the project. These corrections enhance code quality, ensure consistency, and prevent potential runtime issues.

#### **What Changed? Why?**
- **`styles.module.css`**
  - Corrected the invalid CSS property `display: hidden;` to `display: none;` in the `.bannerSpacer` class.
  - Removed the typo `dispaly: none;` from the `.bannerSpacer` class.

- **`503.tsx`**
  - Fixed the typo in the error message from `Error has occured` to `Error has occurred`.

- **`BridgeCards.tsx`**
  - Updated the CSS class from `bg-hovergray` to `bg-hover-gray` for consistency and to match naming conventions.

- **`DesktopNav.tsx`**
  - Removed the duplicated `items-center` class from the navigation container to prevent redundant styling.

- **`_document.tsx`**
  - Eliminated duplicate `meta` tags for `twitter:domain` to adhere to HTML standards and avoid potential SEO issues.

2024-11-01 14:56 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-11-02 07:37 UTC, wbnns requested changes
@dsarfed 

Thanks for this PR! Left a couple of nits in-line.

2024-11-02 07:37 UTC, wbnns commented on apps/base-docs/src/components/Banner/styles.module.css
> +  dispaly: none;
Introduces a typo rather than removing

2024-11-02 07:37 UTC, wbnns commented on apps/bridge/pages/_document.tsx
> +        <meta name="twitter:domain" content="base.org" />
The correct syntax is property

2024-11-02 10:40 UTC, dsarfed commented
Hi @wbnns I've addressed the feedback:
- Reverted the `twitter:domain` meta tag to use `property` instead of `name`.
- Corrected the `display` in `styles.module.css`.

2025-01-14 13:15 UTC, wbnns commented
@dsarfed Could you please rebase and resolve the merge conflict?

2025-03-06 16:51 UTC, closed without merging