3balance DApp update due to the recent rebranding
base/web pull request #1222
Opened 2024-11-07 16:42 UTC by sergeyskill13

In our recent rebranding, we updated the logo, naming, and website: https://3balance.co/blog/threebalance-now-3balance. The PR reflects those changes.

2024-11-07 16:42 UTC, cb-heimdall commented
<h1>🟡 Heimdall Review Status</h1>
<table>
<tr>
<th>Requirement</th>
<th>Status</th>
<th>More Info</th>
</tr>
<tr>
<td>Reviews</td>
<td>
🟡
<code>0/1</code>
</td>
<td>
<details>
<summary>Denominator calculation</summary>
<table>
<tr>
<td>
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><code>1</code> if user is bot</td>
<td>0</td>
</tr>
<tr>
<td><code>1</code> if user is external</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>.codeflow.yml</code>
</td>
<td>1</td>
</tr>
<tr>
<td>
Additional review requirements
<details>
<summary>Show calculation</summary>
<table>
<tr>
<td><strong>Max</strong></td>
<td><strong>0</strong></td>
</tr>
</table>
</details>
</td>
<td>0</td>
</tr>
<tr>
<td>
From <code>CODEOWNERS</code>
</td>
<td>0</td>
</tr>
<tr>
<td>Global minimum</td>
<td>0</td>
</tr>
<tr>
<td><strong>Max</strong></td>
<td>
<strong>
1
</strong>
</td>
</tr>
</table>
</details>
</td>
<td>1</td>
</tr>
<tr>
<td><code>1</code> if commit is unverified</td>
<td>0</td>
</tr>
<tr>
<td><strong>Sum</strong></td>
<td><strong>1</strong></td>
</tr>
</table>
</details>
</td>
</tr>
</table>
<!-- CODEOWNERS & Bar Raisers -->
<!-- Power Rangers -->
<!-- Links -->

2024-11-08 13:59 UTC, wbnns requested changes
@sergeyskill13 

Thanks for this PR! Could you please remove the artifact of the old image from the images folder?

2024-11-08 15:29 UTC, sergeyskill13 commented
> @sergeyskill13
> 
> Thanks for this PR! Could you please remove the artifact of the old image from the images folder?

@wbnns done, please review.

2024-12-19 21:11 UTC, wbnns commented
@sergeyskill13 

Hi there! Apologies, we recently updated the way we [categorize and subcategorize apps](https://github.com/base-org/web?tab=readme-ov-file#updating-the-base-ecosystem-page); could you please rebase + update your PR, conforming to the new format by removing the tag, and defining the category and subcategory?

We'll do our best to review as soon as possible once you do! 🙏

2024-12-24 11:52 UTC, wbnns commented
@sergeyskill13 

Please also rebase to resolve the merge conflict.

2025-01-14 13:12 UTC, closed without merging